{% set name = "rsconnect-jupyter" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rstudio/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 38487e2713996aaa6d1c5000ca359deec961390c2b8bf7149751de867ffad173

build:
  noarch: python
  number: 0

requirements:
  host:
    - make
    - python >=3.6
    - pip

  run:
    - python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*
    - rsconnect-python >=1.5.4
    - notebook
    - nbformat
    - nbconvert >=5.6.1
    - six
    - ipython

test:
  imports:
    - rsconnect_jupyter

about:
  home: https://github.com/rstudio/rsconnect-jupyter/
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Jupyter Notebook integration with RStudio Connect

extra:
  recipe-maintainers:
    - mmarchetti
    - tdstein
