{% set name = "rsconnect-jupyter" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rstudio/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: a8801adf439f4e0038c33784d52e32a4d35a322c53a26f90bc620493b902c72d

build:
  noarch: python
  number: 0

requirements:
  host:
    - make
    - python >=3.6
    - pip

  run:
    - python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*
    - rsconnect-python >=1.5.4
    - notebook
    - nbformat
    - nbconvert >=5.6.1
    - six
    - ipython

test:
  imports:
    - rsconnect_jupyter

about:
  home: https://github.com/rstudio/rsconnect-jupyter/
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Jupyter Notebook integration with RStudio Connect

extra:
  recipe-maintainers:
    - bcwu
