{% set name = "rsconnect-jupyter" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rstudio/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: de4ba3c2b8f1d6f2ab06eee7555b6145ba0765fd4b6a8eca4b952088a775fa69

build:
  noarch: python
  number: 0

requirements:
  host:
    - make
    - python >=3.6
    - pip

  run:
    - python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*
    - rsconnect-python >=1.5.4
    - notebook
    - nbformat
    - nbconvert >=5.6.1
    - six
    - ipython

test:
  imports:
    - rsconnect_jupyter

about:
  home: https://github.com/rstudio/rsconnect-jupyter/
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Jupyter Notebook integration with RStudio Connect

extra:
  recipe-maintainers:
    - bcwu
    - scottmmjackson
